### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/bundle/cache/minitest-5.14.4.gem

### ISSUE THREAD

**Issue by andrey-grach** [TomFern/dockerizing-ruby#12]
When i try to install/update bundle after adding new gems I got error.

Retrying download gem from https://rubygems.org/ due to error (2/4): Errno::EACCES Permission denied @ rb_sysopen - /usr/local/bundle/cache/minitest-5.14.4.gem

Retrying download gem from https://rubygems.org/ due to error (3/4): Errno::EACCES Permission denied @ rb_sysopen - /usr/local/bundle/cache/minitest-5.14.4.gem

Retrying download gem from https://rubygems.org/ due to error (4/4): Errno::EACCES Permission denied @ rb_sysopen - /usr/local/bundle/cache/minitest-5.14.4.gem

Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/bundle/cache/minitest-5.14.4.gem
An error occurred while installing minitest (5.14.4), and Bundler cannot continue.
Make sure that `gem install minitest -v '5.14.4' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rails was resolved to 6.0.3.5, which depends on
    actioncable was resolved to 6.0.3.5, which depends on
      actionpack was resolved to 6.0.3.5, which depends on
        actionview was resolved to 6.0.3.5, which depends on
          rails-dom-testing was resolved to 2.0.3, which depends on
            activesupport was resolved to 6.0.3.5, which depends on

**Comment by TomFern** [comment]
Hi @andrey-grach
Are you running the command in the Docker container? If so, you could try with sudo. Alternatively you could check if the gems are vendored in the project directory.

**Comment by andrey-grach** [comment]
> Hi @andrey-grach
> Are you running the command in the Docker container? If so, you could try with sudo. Alternatively you could check if the gems are vendored in the project directory.

I don't have sudo inside my docker container so it would not work. I resolved this problem in another way. Actually I think gems were not vendored inside the project directory, in my error description you could see this - /usr/local/bundle/cache/minitest-5.14.4.gem. So I think gems vendored globally that is why this problem appeared,  I think should be some configuration that tells docker to vendor gems inside project directory?

**Comment by TomFern** [comment]
@andrey-grach I think I know what may be happening. When you try to install the gems on an already-built container, you're running as a normal/non-root user. So the gem install command fails. You can connect to an already-running container as root with:

```bash
docker run -it -u 0 <container_id>
```
Alternatively, you could switch to vendored modules, you would need to update the Dockerfiles. The command to install gems in `vendor/` is:

```bash
bundle install --path vendor/bundle
```

Note that any gems you install on an already-built image will be lost once the container stops, unless the changes are commited. Let me know if this helps.
